// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Comment struct {
	ID        string     `json:"id"`
	Author    string     `json:"author"`
	Text      string     `json:"text"`
	Replies   []*Comment `json:"replies"`
	CreatedAt string     `json:"createdAt"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	Author          string     `json:"author"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	Comments        []*Comment `json:"comments"`
	CommentsAllowed bool       `json:"commentsAllowed"`
	CreatedAt       string     `json:"createdAt"`
}

type Query struct {
}

type Subscription struct {
}
