package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"threads/internal/graphql/loader"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, author string, title string, content string, commentsAllowed bool) (*Post, error) {
	post, err := r.PostService.CreatePost(ctx, author, title, content, commentsAllowed)
	if err != nil {
		return nil, err
	}

	return MapPostToGraphQL(post), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, postID string, parentID *string, author string, text string) (*Comment, error) {
	comment, err := r.CommentService.CreateComment(ctx, postID, parentID, author, text)
	if err != nil {
		return nil, err
	}

	_ = r.Broker.Publish(ctx, postID, comment)

	return MapCommentToGraphQL(comment), nil
}

// UpdateCommentsAllowed is the resolver for the updateCommentsAllowed field.
func (r *mutationResolver) UpdateCommentsAllowed(ctx context.Context, postID string, allowed bool) (*Post, error) {
	post, err := r.PostService.UpdateCommentsAllowed(ctx, postID, allowed)
	if err != nil {
		return nil, err
	}

	return MapPostToGraphQL(post), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *Post, limit int32, offset int32) ([]*Comment, error) {
	if limit < 0 {
		return nil, errors.New("limit must be non-negative")
	}
	if offset < 0 {
		return nil, errors.New("offset must be non-negative")
	}

	comments, err := loader.For(ctx).CommentsByPostID.Load(ctx, obj.ID)()
	if err != nil {
		return nil, err
	}

	intOffset := int(offset)
	if intOffset > len(comments) {
		intOffset = len(comments)
	}
	intLimit := min(int(limit), len(comments)-intOffset)

	return MapCommentListToGraphQL(comments[intOffset : intOffset+intLimit]), nil
}

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *Comment, limit int32, offset int32) ([]*Comment, error) {
	if limit < 0 {
		return nil, errors.New("limit must be non-negative")
	}
	if offset < 0 {
		return nil, errors.New("offset must be non-negative")
	}

	comments, err := loader.For(ctx).RepliesByParentID.Load(ctx, obj.ID)()
	if err != nil {
		return nil, err
	}

	intOffset := int(offset)
	if intOffset > len(comments) {
		intOffset = len(comments)
	}
	intLimit := min(int(limit), len(comments)-intOffset)

	return MapCommentListToGraphQL(comments[intOffset : intOffset+intLimit]), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit int32, offset int32) ([]*Post, error) {
	posts, err := r.PostService.Posts(ctx, limit, offset)
	if err != nil {
		return nil, err
	}

	return MapPostListToGraphQL(posts), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*Post, error) {
	post, err := r.PostService.Post(ctx, id)

	if err != nil {
		return nil, err
	}

	return MapPostToGraphQL(post), nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *Comment, error) {
	entityChan, err := r.Broker.Subscribe(ctx, postID)
	if err != nil {
		return nil, err
	}

	commentChan := make(chan *Comment)
	go func() {
		defer r.Broker.Unsubscribe(context.Background(), postID, entityChan)
		defer close(commentChan)

		for {
			select {
			case <-ctx.Done():
				return
			case entity := <-entityChan:
				commentChan <- MapCommentToGraphQL(entity)
			}
		}
	}()

	return commentChan, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
